### ISSUE TITLE
xmlparser not backward compatible

### ISSUE THREAD

**Issue by jeroenooms** [hunspell/hunspell#364]
Because libhunspell does not include the parsers and most distributions don't include `libparsers.a` I am forced to bundle the parsers with my application. However after upgrading the parsers to 1.3.4 the application no longer builds on most distributions because they have hunspell 1.3.3.

The problem is that `xmlparser.cxx` now contains references to the newly introduced `mystrrep`.

```
parsers/xmlparser.cpp:212:5: error: no matching function for call to 'mystrrep'
parsers/xmlparser.cpp:213:5: error: no matching function for call to 'mystrrep'
```

Also it is missing an `#include <string>`:

```
parsers/xmlparser.cpp:211:10: error: no member named 'string' in namespace 'std'
    std::string r(word);
```

Not sure if this is a bug or intentional, but it is certainly unfortunate given that the parsers are needed for most tools using `libhunspell`. It would be really nice if the xml parser also works with older versions of hunspell in the 1.3 branch.

**Comment by PanderMusubi** [comment]
Can you list some of the distributions and versions for which this is a problem and provide a minimal example to reproduce this?
